const blogPostData = [
  [
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/08/shutterstock_1727124235-1300x650.jpg.webp",
      title: "Auto Shipment Brokers vs Carriers",
      date: "August 9, 2024",
      text: "Auto Shipment Brokers vs Carriers Auto Shipment Brokers vs Carriers: What’s the Difference? Are you confused when you come across words like brokers and...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/08/New-Hampshire-Shipping-US-Car-Go-Freight-1300x650.jpg.webp",
      title: "New Hampshire Car Transport",
      date: "August 5, 2024",
      text: "Rhode Island Car Transport US Car-Go Freight: Your Trusted Car Transport to Rhode Island When planning to transport your car to Rhode Island, partnering...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/07/Louisiana-Car-Transport-US-CarGo-Freight-1300x650.jpg.webp",
      title: "Louisiana Car Transport",
      date: "July 31, 2024",
      text: "Louisiana Car Transport Louisiana Car Transport: A Comprehensive Guide by US Car-Go Freight When it comes to transporting vehicles in Louisiana, US Car-Go Freight...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/07/how-to-start-car-hauling-business-img-1300x650.jpg.webp",
      title: "How to Start a Car Hauling Business",
      date: "July 26, 2024",
      text: "How to Start a Car Hauling Business Starting a car hauling business Car hauling business can be a lucrative venture for entrepreneurs interested in...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/07/Rhode-Island-Car-Transport-US-CarGo-Freight-1300x650.jpg.webp",
      title: "Rhode Island Car Transport",
      date: "July 25, 2024",
      text: "Rhode Island Car Transport US Car-Go Freight: Your Trusted Car Transport to Rhode Island When planning to transport your car to Rhode Island, partnering...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/07/Delaware-Car-Transport-US-CarGo-Freight-1300x650.jpg.webp",
      title: "Delaware Car Transport",
      date: "July 22, 2024",
      text: "Delaware Car Transport US Car-Go Freight: Your Trusted Partner for Reliable And Secure Delaware Car Transport Relocating for work, buying a car out of...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/07/Vermont-Car-Shipping-US-CarGo-Freight-1300x650.jpg.webp",
      title: "Vermont Car Transport",
      date: "July 19, 2024",
      text: "Vermont Car Transport US Car-Go Freight: Your Top Choice for Vermont Car Transport Are you looking to ship your car to or from the...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/07/New-Jersey-Car-Shipping-US-CarGo-Freight-1300x650.jpg.webp",
      title: "New Jersey Car Transport",
      date: "July 12, 2024",
      text: "New Jersey Car Transport Ship Your Car Safely to New Jersey with US Car-Go Freight Looking for hassle-free car shipping to New Jersey? Look...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/07/Maryland-Car-Transport-US-CarGo-Freight-1300x650.jpg.webp",
      title: "Maryland Car Transport",
      date: "July 11, 2024",
      text: "Maryland Car Transport US Car-Go Freight: The Number One District of Columbia Car Transport Company Maryland is a state in the Mid-Atlantic region of...",
    },
  ],
  [
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/07/District-of-Columbia-Car-Transport-US-CarGo-Freight-1300x650.jpg.webp",
      title: "District of Columbia Car Transport",
      date: "July 9, 2024",
      text: "District of Columbia Car Transport US Car-Go Freight: The Number One District of Columbia Car Transport Company Transport your car safely to or from...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/07/Price-Difference-Small-vs-Large-Vehicle-Shipping-Imgs-1300x650.jpg",
      title: "Small vs Large Vehicle Shipping Price Difference",
      date: "July 3, 2024",
      text: "Small vs Large Vehicle Shipping Price Difference The Price Difference When Shipping a Small Vehicle and a Large Vehicle When it comes to shipping...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/07/Minnesota-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Minnesota Car Transport",
      date: "July 2, 2024",
      text: "Minnesota Car Transport Smooth and Reliable Minnesota Car Transport with US Car-Go Freight Minnesota, known as the Land of 10,000 Lakes, offers a stunning...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/06/Blog-Atv-2-1300x650.jpg",
      title: "Flatbed Auto Transport",
      date: "June 25, 2024",
      text: "Flatbed Auto Transport A Deep Dive into Flatbed Auto Transport If you are moving to a new home or starting a new job, you...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/06/Missouri-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Missouri Car Transport",
      date: "June 25, 2024",
      text: "Missouri Car Transport Discover Seamless Missouri Car Transport with US Car-Go Freight When it comes to transporting your vehicle, the task can seem daunting....",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/06/Kansas-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Kansas Car Transport",
      date: "June 20, 2024",
      text: "Kansas Car Transport Seamless Kansas Car Transport with US Car-Go Freight Kansas, often referred to as the Sunflower State, is renowned for its rolling...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/06/Nebraska-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Nebraska Car Transport",
      date: "June 12, 2024",
      text: "Nebraska Car Transport Comprehensive Guide to Nebraska Car Transport with US Car-Go Freight Transporting your vehicle, whether for a move, a purchase, or other...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/06/Oklahoma-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Oklahoma Car Transport",
      date: "June 7, 2024",
      text: "Oklahoma Car Transport Seamless Oklahoma Car Transport with US Car-Go Freight Oklahoma, known as the Sooner State, is a vibrant blend of rich history,...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/06/New-Mexico-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "New Mexico Car Transport",
      date: "June 6, 2024",
      text: "New Mexico Car Transport Reliable New Mexico Car Transport with US Car-Go Freight New Mexico, known as the Land of Enchantment, is a state...",
    },
  ],
  [
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/05/Wyoming-car-transport-US-CarGo-Freight-1300x650.jpg",
      title: "Wyoming Car Transport",
      date: "May 28, 2024",
      text: "Wyoming Car Transport Conquering the Cowboy State with US Car-Go Freight : A Guide to Wyoming Car Transport in 2024 Wyoming, the “Equality State,”...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/05/Utah-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Utah Car Transport",
      date: "May 24, 2024",
      text: "Utah Car Transport Calling All Adventurers! US Car-Go Freight Your Guide to Hassle-Free Car Transport So, you’ve set your sights on Utah, the “Beehive...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/05/Idaho-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Idaho Car Transport",
      date: "May 16, 2024",
      text: "Idaho Car Transport Exploring the Gem State: Idaho Car Transport with US Car-Go Freight Welcome to the Gem State – Idaho! From the rugged...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/05/Nevada-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Nevada Car Transport",
      date: "May 13, 2024",
      text: "Nevada Car Transport Cruising the Silver State: Nevada Car Transport with US Car-Go Freight Welcome to the Silver State – Nevada! From the glittering...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/05/Washington-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Washington Car Transport",
      date: "May 7, 2024",
      text: "Washington Car Transport Streamlining Your Vehicle Transport: Washington Car Transport with US Car-Go Freight Nestled in the Pacific Northwest, Washington State boasts a diverse...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/05/Oregon-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Oregon Car Transport",
      date: "May 2, 2024",
      text: "Oregon Car Transport Oregon Car Transport Made Easy with US Car-Go Freight Welcome to the Pacific Wonderland – Oregon! From the lush forests of...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/04/Maine-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Maine Car Transport",
      date: "April 25, 2024",
      text: "Maine Car Transport Streamlined Maine Car Transport with US Car-Go Freight In the world of car transport, where delays and unexpected costs can disrupt...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/04/North-Carolina-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "North Carolina Car Transport",
      date: "April 17, 2024",
      text: "North Carolina Car Transport Seamless North Carolina Car Transport with US Car-Go Freight Nestled in the southeastern United States, North Carolina boasts stunning coastlines,...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/04/South-Carolina-Car-Transpotr-US-CarGo-Freight-1300x650.jpg",
      title: "South Carolina Car Transport",
      date: "April 12, 2024",
      text: "South Carolina Car Transport Smooth Sailing: Navigating Car Transport in South Carolina with US Car-Go Freight From the scenic coastline to the picturesque foothills,...",
    },
  ],
  [
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/04/South-Dakota-Car-Transport-US-Car-Go-Freight-Img-1300x650.jpg",
      title: "South Dakota Car Transport",
      date: "April 4, 2024",
      text: "South Dakota Car Transport Navigating South Dakota’s Auto Transport Landscape with US Car-Go Freight In the vast expanse of the United States, where the...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/03/North-Dakota-Car-Transport-US-Car-Go-Freight-Img-1300x650.jpg",
      title: "North Dakota Car Transport",
      date: "March 21, 2024",
      text: "North Dakota Car Transport Smooth Sailing with US Car-Go Freight North Dakota, the Peace Garden State, beckons with vast prairies, vibrant culture, and a...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/03/Texas-Car-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Texas Car Transport",
      date: "March 14, 2024",
      text: "Texas Car Transport Navigating the Lone Star State with Ease and Confidence Texas is synonymous with big skies, big dreams, and everything being, well…...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/02/car-shipping-quotes-bg5-1300x650.jpg",
      title: "Common Misconceptions About Auto Transport and Car Shipping",
      date: "February 26, 2024",
      text: "Common Misconceptions About Auto Transport and Car Shipping Sorting fact from fiction in the world of car shipping can save you both stress and...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/02/Montana-Auto-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Montana Car Transport",
      date: "February 21, 2024",
      text: "Montana Car Transport Seamless Vehicle Shipping with US Car-Go Freight Dreaming of making the move to Montana? You’re not alone. Every year, countless individuals...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/02/Phoenix-Car-Shipping-US-CarGo-Freight-1300x650.jpg",
      title: "Phoenix Car Shipping",
      date: "February 13, 2024",
      text: "Phoenix Car Shipping Cruise into Phoenix in Style: Your Ultimate Guide to Stress-Free Car Shipping with US Car-Go Freight The Grand Canyon beckons with...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/02/Georgia-Car-Shipping-US-CarGo-Freight-1300x650.jpg",
      title: "Georgia Car Shipping",
      date: "February 6, 2024",
      text: "Georgia Car Shipping Cruise into Comfort: Your Ultimate Guide to Georgia Car Shipping with US Car-Go Freight Sun-kissed beaches, vibrant cities, and rolling greens...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2024/01/Hot-Shot-Car-Transport-Img-1000x650.jpg",
      title: "Hot Shot Car Transport",
      date: "January 22, 2024",
      text: "Hot Shot Car Transport How US Car-Go Freight Keep Your Car Safe During Transport? Handing over your car keys for a cross-country journey can...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/12/Indiana-Car-Shipping-Img-1300x650.jpg",
      title: "Indiana Car Shipping",
      date: "December 11, 2023",
      text: "Indiana Car Shipping Navigate Indiana with US CarGo Freight: Your Gateway to the Hoosier State Indiana, a land of rich history, vibrant culture, and...",
    },
  ],
  [
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/12/Iowa-Car-Shipping-Img-1300x650.jpg",
      title: "Iowa Car Shipping",
      date: "December 7, 2023",
      text: "Iowa Car Shipping A Smooth and Reliable Ride with US CarGo Freight Iowa, the “Hawkeye State,” beckons with its picturesque landscapes, welcoming communities, and...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/12/Illinois-Car-Shipping-Img-1300x650.jpg",
      title: "Illinois Car Shipping",
      date: "December 6, 2023",
      text: "Illinois Car Shipping Navigate Illinois with US CarGo Freight: Your Gateway to the Prairie State Illinois, a state brimming with history, culture, and natural...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/10/Arizona-Auto-Transport-US-CarGo-Freight-1300x650.jpg",
      title: "Arizona Auto Transport",
      date: "December 6, 2023",
      text: "Arizona Auto Transport The Superiority of Arizona Auto Transport with US CarGo Freight Welcome to US CarGo Freight, we offer premium Arizona auto transport...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/10/Colorado-Car-Shipping-US-CarGo-Shipping-1300x650.jpg",
      title: "Colorado Car Shipping",
      date: "October 20, 2023",
      text: "Colorado Car Shipping Embrace the Adventure with US CarGo Freight: Colorado Car Shipping Made Simple Colorado, a state renowned for its breathtaking natural beauty,...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/10/toolzbuy228783-1300x650.jpg",
      title: "Arkansas Auto Transport",
      date: "October 16, 2023",
      text: "Arkansas Auto Transport Discover Arkansas with US Car-Go Freight: Your Trusted Vehicle Transport Service Embark on your Arkansas adventure with the support of US...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/10/Alabama-Car-Shipping-US-CarGo-Freight-1300x650.jpg",
      title: "Alabama Car Shipping",
      date: "October 3, 2023",
      text: "Alabama Car Shipping Smooth and Secure Alabama Car Shipping with US CarGo Freight Welcome to US CarGo Freight, your trusted partner for seamless and...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/09/rearview-car-parked-in-luxury-showroom-car-dealer-2023-03-30-01-57-28-utc-1300x650.jpg",
      title: "Shipping Cars Between Dealerships?",
      date: "September 13, 2023",
      text: "Shipping Cars Between Dealerships? How Auto Transport Companies Help? In the vast automotive industry, the movement of vehicles is a critical operation. Whether you...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/09/shutterstock_2209359449-1300x650.jpg",
      title: "How Much Does It Cost to Transport a Boat?",
      date: "September 13, 2023",
      text: "How Much Does It Cost to Transport a Boat? Transporting a boat can be a logistical puzzle, especially if you are new to marine...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/09/How-to-Save-Money-on-Car-Shipping-img-1300x650.jpg",
      title: "How to Save Money on Car Shipping?",
      date: "September 8, 2023",
      text: "How to Save Money on Car Shipping? Your Comprehensive Money-Saving Manual Shipping a car can be a significant expense, especially if you’re moving a...",
    },
  ],
  [
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/09/How-to-Choose-a-Reputable-Car-Shipping-Company-img-1300x650.jpg",
      title: "How to Choose a Reputable Car Shipping Company?",
      date: "September 8, 2023",
      text: "How to Choose a Reputable Car Shipping Company? A Comprehensive Guide Shipping a car can be a daunting task, especially if you’re doing it...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/09/san-francisco-california-car-shipping-1300x650.webp",
      title: "California Car Shipping: A Smooth Ride with US Car-Go Freight",
      date: "September 7, 2023",
      text: "California Car Shipping: A Smooth Ride with US Car-Go Freight Welcome to the golden state of California, where sunny beaches, stunning landscapes, and iconic...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/09/florida-car-shipping-img-1300x650.webp",
      title: "Florida Car Shipping: The Ultimate Roadmap",
      date: "September 7, 2023",
      text: "Florida Car Shipping: The Ultimate Roadmap Florida, the Sunshine State, is renowned for its unique blend of stunning beaches, vibrant cities, and diverse culture....",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/08/Home-CTA-Bg-1300x650.jpg",
      title: "What is a USDOT Number, and How Do I Check It?",
      date: "August 18, 2023",
      text: "What is a USDOT Number, and How Do I Check It? The United States Department of Transportation number, more commonly known as a USDOT...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/08/Shipping-Your-Car-with-US-Cargo-Bg1-1300x650.jpg",
      title:
        "Ship a Luxury Car Now With US Car-GO Freight: Ensuring Safe and Secure Transportation",
      date: "August 11, 2023",
      text: "Ship a Luxury Car Now With US Car-GO Freight: Ensuring Safe and Secure Transportation If you own a luxury car, you understand the value...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/08/autotransportvspersonalinsurance-img-1300x650.jpg",
      title:
        "Auto Transport Insurance vs. Personal Car Insurance: Understanding the Differences",
      date: "August 10, 2023",
      text: "Auto Transport Insurance vs. Personal Car Insurance: Understanding the Differences When it comes to shipping a vehicle, whether it is across the state or...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/05/Lower-car-blog-img-1300x650.jpg",
      title: "What Are the Important Equipment Needed to Ship Lowering Cars?",
      date: "May 2, 2023",
      text: "What Are the Important Equipment Needed to Ship Lowering Cars? When shipping cars, slammed cars, or lowered cars, it’s important to have the right tools...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/05/Local-Vs-National-Auto-Transport-img-1300x650.jpg",
      title:
        "Comparing Local and National Services When Choosing the Right Auto Shipping Option",
      date: "May 2, 2023",
      text: "Comparing Local and National Services When Choosing the Right Auto Shipping Option In recent years, auto shipping has become more and more popular as...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/blog-can-i-ship-personal-iteam-1300x650.jpg",
      title: "Can I Ship My Personal Item With My Car?",
      date: "April 17, 2023",
      text: "Can I Ship My Personal Item With My Car? When it comes to shipping a car, many people wonder if they can also ship...",
    },
  ],
  [
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/shutterstock_547443445-1300x650.jpg",
      title: "The Ins and Outs of Shipping a Lowering Car",
      date: "April 17, 2023",
      text: "The Ins and Outs of Shipping a Lowering Car Shipping a lowered car can be a daunting task for many car enthusiasts. Handling and...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/blog-golf-cart-1-1300x650.jpg",
      title: "The Best Way to Ship a Golf Cart",
      date: "April 14, 2023",
      text: "The Best Way to Ship a Golf Cart Golf carts are a popular way to get around on golf fields and in retirement communities,...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/Blog-Atv-1-1300x650.jpg",
      title: "The Best Way to Ship Your ATV, UTV, and RTVs",
      date: "April 14, 2023",
      text: "The Best Way to Ship Your ATV, UTV, and RTVs If you have ever been off-roading or hunting with an All-Terrain or Utility Terrain...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/blog-classic-1-1300x650.jpg",
      title:
        "What’s the Fundamental Difference Between Classic, Exotic, and Antique Cars?",
      date: "April 14, 2023",
      text: "What’s the Fundamental Difference Between Classic, Exotic, and Antique Cars? Cars are more than just a way to get around. They are an important...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/Blog-florida-to-california-1300x650.jpg",
      title: "Car Shipping From Florida To California",
      date: "April 14, 2023",
      text: "Car Shipping From Florida To California Of course many people transport vehicles from both Florida and California, given their respective sizes. Is getting your...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/why-should-i-ship-my-car-1300x650.jpg",
      title:
        "Why Should I Ship My Car With Your Company Instead Of Any Other Company Out There?",
      date: "April 10, 2023",
      text: "Why Should I Ship My Car With Your Company Instead Of Any Other Company Out There? The thought of having to ship a car...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/shutterstock_2212818803-1300x650.jpg",
      title: "The Cost Of Shipping Your Car To Another State",
      date: "April 10, 2023",
      text: "The Cost Of Shipping Your Car To Another State The cost of shipping a car one thousand miles is somewhere between ten and fifteen...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/blog-California-with-us-cargo-1300x650.jpg",
      title: "Shipping From California with US Cargo",
      date: "April 7, 2023",
      text: "Shipping From California with US Cargo There is a long list of considerations that must be made before a major relocation. Consider what to...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/Home-Page-Bg-1300x650.jpg",
      title: "How Long Does it Take to Deliver Vehicles Across States?",
      date: "April 7, 2023",
      text: "How Long Does it Take to Deliver Vehicles Across States? Whether you’ve just bought a brand-new car or need your current vehicle shipped to...",
    },
  ],
  [
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/Ship-your-Vintage-Car-with-US-Cargo-BG6-1300x650.jpg",
      title: "How to Ship Vehicles from an Auction?",
      date: "April 5, 2023",
      text: "How to Ship Vehicles from an Auction? Buying a car at auction can save you a lot of money, but what comes next? How...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/03/US-Cargo-Veichles-Shipped-Bg-1300x650.jpg",
      title: "How To Prepare Your Car For Shipment?",
      date: "March 21, 2023",
      text: "How To Prepare Your Car For Shipment? Prepare Your Car For Shipment Clean your car Make sure your vehicle is looking fresh before you...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/03/shutterstock_1727124235-1-1300x650.jpg",
      title: "How To Ship My Car To Another State?",
      date: "March 21, 2023",
      text: "How To Ship My Car To Another State? Leaving one state for another is a cool and exciting adventure. Yet, in addition to all...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/How-do-I-get-is-car-transport-quote-1300x650.jpg",
      title: "Why You Need an Auto Shipping Broker?",
      date: "Why You Need an Auto Shipping Broker? There are many reasons why people use auto shipping services to transport their cars. When relocating for...",
    },
    {
      img: "https://uscargofreight.com/wp-content/uploads/2023/04/expidited-customer-uscargo-review-img-1300x650.jpg",
      title: "Tips to Identify Fake Auto Shipping Reviews",
      date: "March 2, 2023",
      text: "Tips to Identify Fake Auto Shipping Reviews People who need to move their cars from one place to another depend on the auto shipping...",
    },
  ],
];

export { blogPostData };
