export { default as Home } from "./Home"
export { default as About } from "./About"
export { default as OurGallery } from "./OurGallery"
export { default as Contact } from "./Contact"
export { default as WhatWeDo } from "./WhatWeDo"